name = "play"
license = "Apache-2.0"
licenselink = "https://github.com/nonlinear/creative-code/blob/main/LICENSE"
description = "An environment for stand-alone creative code experiments, reducing the learning curve so you can enjoy being in the zone faster."
homepage = "https://github.com/nonlinear/play#play"
tags = [
"creative code", 
"ML5", 
"P5", 
"P5js", 
"processing"
]
features = [
"coding", 
"creative coding",
"experiments"
]
min_version = "0.49"

[author]
  name = "Nicholas Frota"
  homepage = "https://nonlinear.nyc"
